[general]
server_check_url = http://www.gstatic.com/generate_204
network_check_url = http://connect.rom.miui.com/generate_204
icmp_auto_reply = true

[dns]

[policy]
static = Proxy, proxy, direct, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png
static = Apple, direct, proxy, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png

[server_remote]
https://raw.githubusercontent.com/uiivoO/man_cave/main/proxy_list.conf, tag=saber 节点, update-interval=86400, opt-parser=false, enabled=true

[filter_remote]
https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/QuantumultX/Apple/Apple.list, tag=Apple, force-policy=Apple, update-interval=604800, opt-parser=false, enabled=true

[rewrite_remote]

[server_local]

[filter_local]
final, Proxy

[rewrite_local]

[task_local]

[http_backend]

[mitm]
